JubilifeCity_Condo1_2F_MapScripts::
	.byte 0


JubilifeCity_Condo1_2F_EventScript_SomePokemonEvolve::
# 4 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	msgbox JubilifeCity_Condo1_2F_Text_SomePokemonEvolve
	return


JubilifeCity_Condo1_2F_EventScript_MysteriesOfEvolution::
# 8 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	msgbox JubilifeCity_Condo1_2F_Text_MysteriesOfEvolution
	return


JubilifeCity_Condo1_2F_EventScript_RowanResearchedWithOak::
# 12 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	msgbox JubilifeCity_Condo1_2F_Text_RowanResearchedWithOak
	return


JubilifeCity_Condo1_2F_Text_SomePokemonEvolve::
# 15 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	.string "Did you know?\p"
	.string "Some kinds of Pokemon evolve when they\n"
	.string "get stronger from battling!\p"
	.string "When they evolve, they can take on\n"
	.string "completely different forms!$"

JubilifeCity_Condo1_2F_Text_MysteriesOfEvolution::
# 19 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	.string "Evolution makes Pokemon just that much\n"
	.string "more fascinating.\p"
	.string "The mysteries of evolution... Can that\n"
	.string "dandy Prof. Rowan unravel them?$"

JubilifeCity_Condo1_2F_Text_RowanResearchedWithOak::
# 23 "data/maps/JubilifeCity_Condo1_2F/scripts.pory"
	.string "Didn't Prof. Rowan conduct research\n"
	.string "with Prof. Oak of the Kanto region?$"
