TwinleafTown_PlayersHouse_2F_MapScripts::
	.byte 0


TwinleafTown_PlayersHouse_2F_Intro_1::
# 3 "data/maps/TwinleafTown_PlayersHouse_2F/scripts.pory"
	.string "Barry: There you are!$"

TwinleafTown_PlayersHouse_2F_Intro_2::
# 7 "data/maps/TwinleafTown_PlayersHouse_2F/scripts.pory"
	.string "Hey, {PLAYER}!\n"
	.string "Did you just see the TV? Sure you did!\p"
	.string "Prof. Rowan's that really important guy\n"
	.string "who studies Pokemon, right?\p"
	.string "That means he must have lots and lots\n"
	.string "of Pokemon.\p"
	.string "So, if we ask him, I bet he'd give us some\n"
	.string "Pokemon!$"

TwinleafTown_PlayersHouse_2F_Intro_3::
# 11 "data/maps/TwinleafTown_PlayersHouse_2F/scripts.pory"
	.string "Oh, hey!\n"
	.string "Is this a new PC?!$"

TwinleafTown_PlayersHouse_2F_Intro_4::
# 15 "data/maps/TwinleafTown_PlayersHouse_2F/scripts.pory"
	.string "Barry: Uh...\n"
	.string "Where was I?$"

TwinleafTown_PlayersHouse_2F_Intro_5::
# 19 "data/maps/TwinleafTown_PlayersHouse_2F/scripts.pory"
	.string "Oh, right, right! We're going to go see\n"
	.string "Prof. Rowan and get some Pokemon.\p"
	.string "I'll be waiting outside.\p"
	.string "OK, {PLAYER}? If you're late, I'm\n"
	.string "fining you ¥10 million!$"
