SandgemTown_House_MapScripts::
	.byte 0


SandgemTown_House_EventScript_PokemonGrowStronger::
# 4 "data/maps/SandgemTown_House/scripts.pory"
	msgbox SandgemTown_House_Text_PokemonGrowStronger, MSGBOX_NPC
	return


SandgemTown_House_EventScript_AGoodTrainerIs::
# 8 "data/maps/SandgemTown_House/scripts.pory"
	msgbox SandgemTown_House_Text_AGoodTrainerIs, MSGBOX_NPC
	return


SandgemTown_House_Text_PokemonGrowStronger::
# 10 "data/maps/SandgemTown_House/scripts.pory"
	.string "Pokémon grow steadily stronger from\n"
	.string "battling against other Pokémon.\p"
	.string "At first, you should take it easy,\n"
	.string "though.\p"
	.string "Heal your Pokémon regularly at Pokémon\n"
	.string "Centers while you’re leveling them up.$"

SandgemTown_House_Text_AGoodTrainerIs::
# 14 "data/maps/SandgemTown_House/scripts.pory"
	.string "A good Trainer is one that takes care\n"
	.string "not to let their Pokémon faint from\l"
	.string "losing HP.$"
