#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_OLDALE_TOWN                  0x01
#define MAPSEC_DEWFORD_TOWN                 0x02
#define MAPSEC_LAVARIDGE_TOWN               0x03
#define MAPSEC_FALLARBOR_TOWN               0x04
#define MAPSEC_VERDANTURF_TOWN              0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_PETALBURG_CITY               0x07
#define MAPSEC_SLATEPORT_CITY               0x08
#define MAPSEC_MAUVILLE_CITY                0x09
#define MAPSEC_RUSTBORO_CITY                0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_LILYCOVE_CITY                0x0C
#define MAPSEC_MOSSDEEP_CITY                0x0D
#define MAPSEC_SOOTOPOLIS_CITY              0x0E
#define MAPSEC_EVER_GRANDE_CITY             0x0F
#define MAPSEC_ROUTE_101                    0x10
#define MAPSEC_ROUTE_102                    0x11
#define MAPSEC_ROUTE_103                    0x12
#define MAPSEC_ROUTE_104                    0x13
#define MAPSEC_ROUTE_105                    0x14
#define MAPSEC_ROUTE_106                    0x15
#define MAPSEC_ROUTE_107                    0x16
#define MAPSEC_ROUTE_108                    0x17
#define MAPSEC_ROUTE_109                    0x18
#define MAPSEC_ROUTE_110                    0x19
#define MAPSEC_ROUTE_111                    0x1A
#define MAPSEC_ROUTE_112                    0x1B
#define MAPSEC_ROUTE_113                    0x1C
#define MAPSEC_ROUTE_114                    0x1D
#define MAPSEC_ROUTE_115                    0x1E
#define MAPSEC_ROUTE_116                    0x1F
#define MAPSEC_ROUTE_117                    0x20
#define MAPSEC_ROUTE_118                    0x21
#define MAPSEC_ROUTE_119                    0x22
#define MAPSEC_ROUTE_120                    0x23
#define MAPSEC_ROUTE_121                    0x24
#define MAPSEC_ROUTE_122                    0x25
#define MAPSEC_ROUTE_123                    0x26
#define MAPSEC_ROUTE_124                    0x27
#define MAPSEC_ROUTE_125                    0x28
#define MAPSEC_ROUTE_126                    0x29
#define MAPSEC_ROUTE_127                    0x2A
#define MAPSEC_ROUTE_128                    0x2B
#define MAPSEC_ROUTE_129                    0x2C
#define MAPSEC_ROUTE_130                    0x2D
#define MAPSEC_ROUTE_131                    0x2E
#define MAPSEC_ROUTE_132                    0x2F
#define MAPSEC_ROUTE_133                    0x30
#define MAPSEC_ROUTE_134                    0x31
#define MAPSEC_UNDERWATER_124               0x32
#define MAPSEC_UNDERWATER_126               0x33
#define MAPSEC_UNDERWATER_127               0x34
#define MAPSEC_UNDERWATER_128               0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x36
#define MAPSEC_GRANITE_CAVE                 0x37
#define MAPSEC_MT_CHIMNEY                   0x38
#define MAPSEC_SAFARI_ZONE                  0x39
#define MAPSEC_BATTLE_FRONTIER              0x3A
#define MAPSEC_PETALBURG_WOODS              0x3B
#define MAPSEC_RUSTURF_TUNNEL               0x3C
#define MAPSEC_ABANDONED_SHIP               0x3D
#define MAPSEC_NEW_MAUVILLE                 0x3E
#define MAPSEC_METEOR_FALLS                 0x3F
#define MAPSEC_METEOR_FALLS2                0x40
#define MAPSEC_MT_PYRE                      0x41
#define MAPSEC_AQUA_HIDEOUT_OLD             0x42
#define MAPSEC_SHOAL_CAVE                   0x43
#define MAPSEC_SEAFLOOR_CAVERN              0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x45
#define MAPSEC_VICTORY_ROAD                 0x46
#define MAPSEC_MIRAGE_ISLAND                0x47
#define MAPSEC_CAVE_OF_ORIGIN               0x48
#define MAPSEC_SOUTHERN_ISLAND              0x49
#define MAPSEC_FIERY_PATH                   0x4A
#define MAPSEC_FIERY_PATH2                  0x4B
#define MAPSEC_JAGGED_PASS                  0x4C
#define MAPSEC_JAGGED_PASS2                 0x4D
#define MAPSEC_SEALED_CHAMBER               0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x4F
#define MAPSEC_SCORCHED_SLAB                0x50
#define MAPSEC_ISLAND_CAVE                  0x51
#define MAPSEC_DESERT_RUINS                 0x52
#define MAPSEC_ANCIENT_TOMB                 0x53
#define MAPSEC_MYSTERY_ZONE                 0x54
#define MAPSEC_SKY_PILLAR                   0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_TWINLEAF_TOWN                0x58
#define MAPSEC_SANDGEM_TOWN                 0x59
#define MAPSEC_OREBURGH_CITY                0x5A
#define MAPSEC_PASTORIA_CITY                0x5B
#define MAPSEC_HEARTHOME_CITY               0x5C
#define MAPSEC_SUNYSHORE_CITY               0x5D
#define MAPSEC_ETERNA_CITY                  0x5E
#define MAPSEC_JUBILIFE_CITY                0x5F
#define MAPSEC_CANALAVE_CITY                0x60
#define MAPSEC_VEILSTONE_CITY               0x61
#define MAPSEC_SNOWPOINT_CITY               0x62
#define MAPSEC_FLOAROMA_TOWN                0x63
#define MAPSEC_CELESTIC_TOWN                0x64
#define MAPSEC_ROUTE_201                    0x65
#define MAPSEC_ROUTE_202                    0x66
#define MAPSEC_ROUTE_203                    0x67
#define MAPSEC_ROUTE_204                    0x68
#define MAPSEC_ROUTE_205_SOUTH              0x69
#define MAPSEC_ROUTE_206                    0x6A
#define MAPSEC_ROUTE_207                    0x6B
#define MAPSEC_ROUTE_208                    0x6C
#define MAPSEC_ROUTE_209                    0x6D
#define MAPSEC_ROUTE_210_SOUTH              0x6E
#define MAPSEC_ROUTE_211                    0x6F
#define MAPSEC_ROUTE_212_SOUTH              0x70
#define MAPSEC_ROUTE_213                    0x71
#define MAPSEC_ROUTE_214                    0x72
#define MAPSEC_ROUTE_215                    0x73
#define MAPSEC_ROUTE_216                    0x74
#define MAPSEC_ROUTE_217                    0x75
#define MAPSEC_ROUTE_218                    0x76
#define MAPSEC_ROUTE_219                    0x77
#define MAPSEC_ROUTE_220                    0x78
#define MAPSEC_ROUTE_221                    0x79
#define MAPSEC_ROUTE_222                    0x7A
#define MAPSEC_ROUTE_223                    0x7B
#define MAPSEC_ROUTE_224                    0x7C
#define MAPSEC_ROUTE_225                    0x7D
#define MAPSEC_ROUTE_226                    0x7E
#define MAPSEC_ROUTE_227                    0x7F
#define MAPSEC_ROUTE_228                    0x80
#define MAPSEC_ROUTE_229                    0x81
#define MAPSEC_ROUTE_230                    0x82
#define MAPSEC_ROUTE_205_NORTH              0x83
#define MAPSEC_ROUTE_210_NORTH              0x84
#define MAPSEC_ROUTE_212_NORTH              0x85
#define MAPSEC_LAKE_VERITY                  0x86
#define MAPSEC_LAKE_VALOR                   0x87
#define MAPSEC_LAKE_ACUITY                  0x88
#define MAPSEC_VALOR_LAKEFRONT              0x89
#define MAPSEC_IRON_ISLAND                  0x8A
#define MAPSEC_ETERNA_FOREST                0x8B
#define MAPSEC_VALLEY_WINDWORKS             0x8C
#define MAPSEC_FUEGO_IRONWORKS              0x8D
#define MAPSEC_MOUNT_CORONET_SOUTH                0x8E
#define MAPSEC_ROCK_PEAK_RUINS              0x8F
#define MAPSEC_ICEBERG_RUINS                0x90
#define MAPSEC_SOLACEON_TOWN                0x91
#define MAPSEC_SOLACEON_RUINS               0x92
#define MAPSEC_SINNOH_POKEMON_LEAGUE        0x93
#define MAPSEC_FIGHT_AREA                   0x94
#define MAPSEC_SURVIVAL_AREA                0x95
#define MAPSEC_RESORT_AREA                  0x96
#define MAPSEC_RAVAGED_PATH                 0x97
#define MAPSEC_OREBURGH_GATE                0x98
#define MAPSEC_WAYWARD_CAVE                 0x99
#define MAPSEC_OREBURGH_MINE                0x9A
#define MAPSEC_CELESTIC_RUINS               0x9B
#define MAPSEC_GALACTIC_ETERNA_BUILDING     0x9C
#define MAPSEC_GALACTIC_VEILSTONE_HQ        0x9D
#define MAPSEC_AMITY_SQUARE                 0x9E
#define MAPSEC_POKEMON_MANSION              0x9F
#define MAPSEC_TROPHY_GARDEN                0xA0
#define MAPSEC_GREAT_MARSH                  0xA1
#define MAPSEC_SPRING_PATH                  0xA2
#define MAPSEC_SENDOFF_SPRING               0xA3
#define MAPSEC_TURNBACK_CAVE                0xA4
#define MAPSEC_DISTORTION_WORLD             0xA5
#define MAPSEC_MANIAC_TUNNEL                0xA6
#define MAPSEC_SINNOH_VICTORY_ROAD          0xA7
#define MAPSEC_SEABREAK_PATH                0xA8
#define MAPSEC_FLOWER_PARADISE              0xA9
#define MAPSEC_FULLMOON_ISLAND              0xAA
#define MAPSEC_NEWMOON_ISLAND               0xAB
#define MAPSEC_SINNOH_BATTLE_FRONTIER       0xAC
#define MAPSEC_STARK_MOUNTAIN               0xAD
#define MAPSEC_SNOWPOINT_TEMPLE             0xAE
#define MAPSEC_LOST_TOWER                   0xAF
#define MAPSEC_IRON_RUINS                   0xB0
#define MAPSEC_SPEAR_PILLAR                 0xB1
#define MAPSEC_HALL_OF_ORIGIN               0xB2
#define MAPSEC_FLOAROMA_MEADOW              0xB3
#define MAPSEC_OLD_CHATEAU                  0xB4
#define MAPSEC_MOUNT_CORONET_NORTH          0xB5
#define MAPSEC_MOUNT_CORONET_PEAK           0xB6
#define MAPSEC_ALTERING_CAVE_FRLG           0xB7
#define MAPSEC_TANOBY_CHAMBERS              0xB8
#define MAPSEC_THREE_ISLE_PATH              0xB9
#define MAPSEC_TANOBY_KEY                   0xBA
#define MAPSEC_BIRTH_ISLAND_FRLG            0xBB
#define MAPSEC_MONEAN_CHAMBER               0xBC
#define MAPSEC_LIPTOO_CHAMBER               0xBD
#define MAPSEC_WEEPTH_CHAMBER               0xBE
#define MAPSEC_DILFORD_CHAMBER              0xBF
#define MAPSEC_SCUFIB_CHAMBER               0xC0
#define MAPSEC_RIXY_CHAMBER                 0xC1
#define MAPSEC_VIAPOIS_CHAMBER              0xC2
#define MAPSEC_EMBER_SPA                    0xC3
#define MAPSEC_SPECIAL_AREA                 0xC4
#define MAPSEC_AQUA_HIDEOUT                 0xC5
#define MAPSEC_MAGMA_HIDEOUT                0xC6
#define MAPSEC_MIRAGE_TOWER                 0xC7
#define MAPSEC_BIRTH_ISLAND                 0xC8
#define MAPSEC_FARAWAY_ISLAND               0xC9
#define MAPSEC_ARTISAN_CAVE                 0xCA
#define MAPSEC_MARINE_CAVE                  0xCB
#define MAPSEC_UNDERWATER_MARINE_CAVE       0xCC
#define MAPSEC_TERRA_CAVE                   0xCD
#define MAPSEC_UNDERWATER_105               0xCE
#define MAPSEC_UNDERWATER_125               0xCF
#define MAPSEC_UNDERWATER_129               0xD0
#define MAPSEC_DESERT_UNDERPASS             0xD1
#define MAPSEC_ALTERING_CAVE                0xD2
#define MAPSEC_NAVEL_ROCK                   0xD3
#define MAPSEC_TRAINER_HILL                 0xD4
#define MAPSEC_NONE                         0xD5

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#define KANTO_MAPSEC_START  MAPSEC_TWINLEAF_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
