LakeVerity_Sign::
# 2 "data/maps/LakeVerity/scripts.pory"
	lock
# 3 "data/maps/LakeVerity/scripts.pory"
	msgbox LakeVerity_Sign_Text_0
# 4 "data/maps/LakeVerity/scripts.pory"
	msgbox LakeVerity_Sign_Text_1
# 5 "data/maps/LakeVerity/scripts.pory"
	msgbox LakeVerity_Sign_Text_2
# 6 "data/maps/LakeVerity/scripts.pory"
	release
	end


# 10 "data/maps/LakeVerity/scripts.pory"

# 11 "data/maps/LakeVerity/scripts.pory"
LakeVerity_MapScripts::
# 12 "data/maps/LakeVerity/scripts.pory"
	.byte 0

LakeVerity_Sign_Text_0:
# 3 "data/maps/LakeVerity/scripts.pory"
	.string "Lake Verity Ahead/p$"

LakeVerity_Sign_Text_1:
# 4 "data/maps/LakeVerity/scripts.pory"
	.string "According to legend, this lake is home\n"
	.string "to the Pokemon said to be “The Being of\l"
	.string "Emotion.”/p$"

LakeVerity_Sign_Text_2:
# 5 "data/maps/LakeVerity/scripts.pory"
	.string "It is because of this Pokemon that\n"
	.string "people can experience sorrow and joy.$"
