TwinleafTown_House2_MapScripts::
	.byte 0


TwinleafTown_House2_EventScript_OldWoman::
# 4 "data/maps/TwinleafTown_House2/scripts.pory"
	msgbox TwinleafTown_House2_Text_OldWoman_Intro, MSGBOX_NPC
	return


TwinleafTown_House2_Text_OldWoman_Intro::
# 7 "data/maps/TwinleafTown_House2/scripts.pory"
	.string "Did you hear?\p"
	.string "The Pokemon Professor returned to the\n"
	.string "next town over.\p"
	.string "They say he was gone for four long\n"
	.string "years.\p"
	.string "I wonder if he found some amazing\n"
	.string "Pokemon while he was gone?$"

TwinleafTown_House2_Text_Girl::
# 11 "data/maps/TwinleafTown_House2/scripts.pory"
	.string "Listen, listen, {PLAYER}.\n"
	.string "I want a cute Pokemon!$"
