TwinleafTown_PlayersHouse_1F_MapScripts::
	.byte 0


text1::
# 3 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: {PLAYER}!\p"
	.string "Barry already left.\p"
	.string "I don't know what it was about, but he\n"
	.string "sure was in a hurry!$"

text2::
# 7 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: You know how impatient Barry is.\p"
	.string "He took off before I could even ask\n"
	.string "what it was about.$"

text3::
# 11 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: Oh, yes!\n"
	.string "{PLAYER}!\p"
	.string "Don't go into the tall grass. Wild\n"
	.string "Pokemon might attack you.\p"
	.string "It would be OK if you had your own\n"
	.string "Pokemon, but you don't, so...\p"
	.string "Well, take care, sweetie!$"

text4::
# 15 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: Bye-bye {PLAYER}!\n"
	.string "You take care now!$"

text5::
# 19 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: What is it, dear?\n"
	.string "Isn't Barry waiting for you?$"

text6::
# 23 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: Welcome home, {PLAYER}.\n"
	.string "Are you and your Pokemon healthy?\n"
	.string "Take a quick rest, dear.$"

text7::
# 27 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom: {PLAYER}.\p"
	.string "Listen. Always treat your Pokemon with\n"
	.string "kindness.\p"
	.string "Your Pokemon work hard, not for\n"
	.string "themselves, but for you!$"

text8::
# 31 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "This is where Mom does all her delicious\n"
	.string "cooking.$"

text9::
# 35 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom's favorite dessert is in the\n"
	.string "refrigerator$"

text10::
# 39 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "Mom's kitchen is spotless!\n"
	.string "You can see your face on the floor!$"

text11::
# 43 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "$"

text12::
# 47 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "$"

text13::
# 51 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "$"

text14::
# 55 "data/maps/TwinleafTown_PlayersHouse_1F/scripts.pory"
	.string "$"
